# Generated by Django 4.1.4 on 2023-01-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="uploadimage", name="caption",),
        migrations.AddField(
            model_name="uploadimage",
            name="bgEnhance",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadimage",
            name="fidility",
            field=models.FloatField(default=0.5, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadimage",
            name="upsample",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
