# Generated by Django 4.1.4 on 2023-01-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0002_remove_uploadimage_caption_uploadimage_bgenhance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("hotel_Main_Img", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.DeleteModel(name="UploadImage",),
    ]
