# Generated by Django 4.1.4 on 2023-01-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0003_hotel_delete_uploadimage"),
    ]

    operations = [
        migrations.RenameModel(old_name="Hotel", new_name="Image",),
    ]
